//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string Product_Name { get; set; }
        public int Product_ID { get; set; }
        public double Product_Price { get; set; }
        public int Product_Quantity { get; set; }
        public string Product_Category { get; set; }
        public string Product_Description { get; set; }
        public string Image_URL { get; set; }
    }
}
